#!/bin/sh

echo "Running ktlintFormat..."
./gradlew ktlintFormat || exit 1

echo "ktlintFormat completed successfully."

echo "Running gradle build..."
./gradlew build || exit 1

echo "build completed successfully."